name: Docker Publish

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'Dockerfile.multi-platform'
      - 'ollama-ui/**'
      - '.github/workflows/docker-publish.yml'
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  # Original mixed-case repo (cannot rely on automatic lowercasing by all tooling)
  IMAGE_NAME_ORIG: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase image name
        id: names
        run: |
          echo "orig=$IMAGE_NAME_ORIG" >> $GITHUB_OUTPUT
          echo "lower=${IMAGE_NAME_ORIG,,}" >> $GITHUB_OUTPUT
        env:
          IMAGE_NAME_ORIG: ${{ env.IMAGE_NAME_ORIG }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.names.outputs.lower }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # If tag matches v* use semver patterns (produces v1.2.3, v1.2, v1)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.description=Ollama UI + Ollama server combined image

      - name: Build and push (single-arch amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summarize
        run: |
          echo "Published (lowercase) image: ghcr.io/${{ steps.names.outputs.lower }}" >> $GITHUB_STEP_SUMMARY
          echo "Tags:" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' >> $GITHUB_STEP_SUMMARY
          echo "\nHint: Ensure the container package visibility is Public under Settings > Packages if pulls return 403." >> $GITHUB_STEP_SUMMARY
