name: Docker Publish

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'Dockerfile.multi-platform'
      - 'ollama-ui/**'
      - '.github/workflows/docker-publish.yml'
  workflow_dispatch:
  release:
    types: [published]
  schedule:
    # Run every night at 02:30 UTC
    - cron: '30 2 * * *'

permissions:
  contents: read
  packages: write

concurrency:
  group: docker-publish-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  # Original mixed-case repo (cannot rely on automatic lowercasing by all tooling)
  IMAGE_NAME_ORIG: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase image name
        id: names
        run: |
          echo "orig=$IMAGE_NAME_ORIG" >> $GITHUB_OUTPUT
          echo "lower=${IMAGE_NAME_ORIG,,}" >> $GITHUB_OUTPUT
        env:
          IMAGE_NAME_ORIG: ${{ env.IMAGE_NAME_ORIG }}

      - name: Fetch base image digest (ollama/ollama:latest)
        id: base_digest
        run: |
          set -euo pipefail
          docker pull -q ollama/ollama:latest > /dev/null
          # Get canonical digest (repo@sha256:...)
          DIGEST_LINE=$(docker image inspect ollama/ollama:latest --format '{{index .RepoDigests 0}}')
          # Extract just sha256:...
          BASE_DIGEST=${DIGEST_LINE##*@}
          echo "Current base image digest: $BASE_DIGEST"
          echo "digest=$BASE_DIGEST" >> $GITHUB_OUTPUT
      - name: Extract Docker metadata (always run to know actual tags)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ steps.names.outputs.lower }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            # If tag matches v* use semver patterns (produces v1.2.3, v1.2, v1)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.description=Ollama UI + Ollama server combined image
            base.image=ollama/ollama:latest
            base.image.digest=${{ steps.base_digest.outputs.digest }}
            build.triggered.by=${{ github.event_name }}

      - name: Derive sha tag reference
        id: sha_ref
        run: |
          set -euo pipefail
          echo "All computed tags (comma separated):"
          echo '${{ steps.meta.outputs.tags }}'
          # Find a tag with :sha-<7hex>
          SHA_TAG=$(echo '${{ steps.meta.outputs.tags }}' | tr ',' '\n' | grep -E ':sha-[0-9a-f]{7}$' | head -n1 || true)
          if [ -z "$SHA_TAG" ]; then
            # Fallback construct (metadata action usually uses short sha)
            SHORT_SHA=$(git rev-parse --short=7 HEAD)
            SHA_TAG="ghcr.io/${{ steps.names.outputs.lower }}:sha-${SHORT_SHA}"
            echo "Fallback sha tag reference constructed: $SHA_TAG"
          else
            echo "Detected sha tag from metadata: $SHA_TAG"
          fi
          echo "image_ref=$SHA_TAG" >> $GITHUB_OUTPUT

      - name: Skip check (all events) - skip if same commit & base image digest
        id: skip_check
        run: |
          set -euo pipefail
          IMAGE='${{ steps.sha_ref.outputs.image_ref }}'
          CUR_BASE_DIGEST='${{ steps.base_digest.outputs.digest }}'
          echo "Evaluating whether to skip build for event: $GITHUB_EVENT_NAME"
          echo "Candidate commit SHA: $(git rev-parse --short=7 HEAD)"
            
          NEED_BUILD=true
          if [ -z "$IMAGE" ]; then
            echo "No image reference derived; will build."
          elif docker manifest inspect "$IMAGE" > /dev/null 2>&1; then
            echo "Image $IMAGE already exists. Checking base image digest label..."
            docker pull -q "$IMAGE" > /dev/null 2>&1 || true
            EXISTING_BASE_DIGEST=$(docker inspect -f '{{ index .Config.Labels "base.image.digest"}}' "$IMAGE" 2>/dev/null || echo 'unknown')
            echo "Current base digest: $CUR_BASE_DIGEST"
            echo "Existing base digest: $EXISTING_BASE_DIGEST"
            if [ "$EXISTING_BASE_DIGEST" = "$CUR_BASE_DIGEST" ] && [ -n "$EXISTING_BASE_DIGEST" ] && [ "$EXISTING_BASE_DIGEST" != "unknown" ]; then
              echo "Commit + base digest unchanged -> skip build & push"
              NEED_BUILD=false
            else
              echo "Base digest differs/missing -> rebuild"
            fi
          else
            echo "No existing image manifest for $IMAGE -> build required"
          fi
          if [ "$NEED_BUILD" = true ]; then echo "skip=false" >> $GITHUB_OUTPUT; else echo "skip=true" >> $GITHUB_OUTPUT; fi

      - name: Show decision context
        run: |
          echo "Skip flag: ${{ steps.skip_check.outputs.skip }}"
          echo "SHA image ref: ${{ steps.sha_ref.outputs.image_ref }}"
          echo "Base digest: ${{ steps.base_digest.outputs.digest }}"

      - name: Guard (stop early if skipping)
        if: steps.skip_check.outputs.skip == 'true'
        run: |
          echo "Skipping build & push steps."

      - name: Build and push (single-arch amd64)
        if: steps.skip_check.outputs.skip != 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summarize
        run: |
          if [ "${{ steps.skip_check.outputs.skip }}" = "true" ]; then
            echo "Build skipped: existing image for commit with identical base digest." >> $GITHUB_STEP_SUMMARY
          else
            echo "Published (lowercase) image: ghcr.io/${{ steps.names.outputs.lower }}" >> $GITHUB_STEP_SUMMARY
            echo "Tags:" >> $GITHUB_STEP_SUMMARY
            echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n' >> $GITHUB_STEP_SUMMARY
            echo "\nHint: Ensure the container package visibility is Public under Settings > Packages if pulls return 403." >> $GITHUB_STEP_SUMMARY
          fi
